version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        port: 4466
        databases:
          default:
            connector: mongo
            uri: "mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo"
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~
